name: Set up Skopeo CLI
author: gonmmarques
description: |-
  Downloads, installs, and configures the Skopeo CLI.
  Adds the `skopeo` command to the $PATH.

branding:
  icon: 'terminal'
  color: 'blue'

inputs:
  version:
    description: 'Version of skopeo to install'
    required: false
    default: 'latest'

runs:
  using: node24
  main: dist/index.js
