name: Test Action

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test-action:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - macos-14

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up skopeo
        id: setup
        uses: ./
        with:
          version: latest

      - name: Verify skopeo is available
        id: verify
        run: |
          command -v skopeo
          skopeo --version
